packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

catalog:
  "@aws-sdk/client-kms": ^3.734.0
  "@aws-sdk/client-secrets-manager": ^3.734.0
  "@biomejs/biome": ^1.9.4
  "@biomejs/cli-linux-x64": ^1.9.4
  "@changesets/cli": ^2.27.12
  "@electron-toolkit/preload": ^3.0.1
  "@electron-toolkit/tsconfig": ^1.0.1
  "@electron-toolkit/utils": ^3.0.0
  "@esbuild/linux-x64": ^0.24.0
  "@fastify/cors": ^10.0.2
  "@fastify/swagger": ^9.4.2
  "@fastify/swagger-ui": ^5.2.1
  "@fastify/type-provider-typebox": ^5.1.0
  "@prisma/client": ^6.3.0
  "@radix-ui/react-dialog": ^1.1.5
  "@radix-ui/react-visually-hidden": ^1.1.1
  "@rollup/rollup-linux-x64-gnu": ^4.24.0
  "@sentry/node": ^8.52.0
  "@sinclair/typebox": ^0.34.14
  "@storybook/addon-essentials": ^8.5.2
  "@storybook/react": ^8.5.2
  "@storybook/react-vite": ^8.5.2
  "@sushiswap/tines": ^1.0.11
  "@thirdweb-dev/engine": ^0.0.17
  "@types/jsonwebtoken": ^9.0.8
  "@types/node": ^22.12.0
  "@types/react": ^18.3.13
  "@types/react-dom": ^18.3.1
  "@types/uuid": "^10.0.0"
  "@vitejs/plugin-react": ^4.3.4
  "@wagmi/core": ^2.16.3
  abitype: ^1.0.8
  autoprefixer: ^10.4.20
  "aws-kms-signer": ^0.5.3
  clsx: ^2.1.1
  dotenv: ^16.4.7
  "dotenv-cli": ^8.0.0
  electron: ^31.1.2
  "electron-builder": ^25.1.8
  "electron-vite": ^2.3.0
  express: ^4.21.2
  fastify: ^5.2.1
  husky: ^9.1.7
  i18next: ^24.2.2
  "i18next-browser-languagedetector": ^8.0.2
  "input-otp": ^1.4.2
  jsdom: ^25.0.1
  jsonwebtoken: ^9.0.2
  "jwks-rsa": ^3.1.0
  "jwt-decode": ^4.0.0
  knip: ^5.43.6
  lint-staged: ^15.4.3
  ox: 0.4.2 # matches Thirdweb version to satisfy getAwsKmsAccount types
  pino: ^9.6.0
  pino-pretty: ^13.0.0
  postcss: ^8.5.1
  prisma: ^6.3.0
  react: ^18.2.0
  "react-dom": ^18.2.0
  "react-i18next": ^15.4.0
  storybook: ^8.5.2
  tailwindcss: ^3.4.17
  "tailwind-config-viewer": ^2.0.4
  "tailwindcss-animate": ^1.0.7
  "tailwind-merge": ^2.6.0
  thirdweb: 5.86.6 # check ox and viem versions if upgrading
  tsup: 8.3.0 # --watch mode broken with Fastify in later versions
  tsx: ^4.19.2
  turbo: ^2.3.4
  typescript: ^5.7.3
  uuid: ^11.0.5
  viem: 2.22.15 # matches Thirdweb version to satisfy getAwsKmsAccount types
  vite: ^6.0.11
  vitest: ^3.0.4
