packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

catalog:
  "@aws-sdk/client-kms": ^3.699.0
  "@aws-sdk/client-secrets-manager": ^3.699.0
  "@biomejs/biome": ^1.9.4
  "@biomejs/cli-linux-x64": ^1.9.4
  "@changesets/cli": ^2.27.10
  "@electron-toolkit/preload": ^3.0.1
  "@electron-toolkit/tsconfig": ^1.0.1
  "@electron-toolkit/utils": ^3.0.0
  "@esbuild/linux-x64": ^0.24.0
  "@fastify/cors": ^10.0.0
  "@fastify/swagger": ^9.4.0
  "@fastify/swagger-ui": ^5.2.0
  "@fastify/type-provider-typebox": ^5.1.0
  "@prisma/client": ^6.0.1
  "@radix-ui/react-dialog": ^1.1.2
  "@radix-ui/react-visually-hidden": ^1.1.0
  "@rollup/rollup-linux-x64-gnu": ^4.24.0
  "@sentry/node": ^8.42.0
  "@sinclair/typebox": ^0.34.11
  "@storybook/addon-essentials": ^8.4.7
  "@storybook/react": ^8.4.7
  "@storybook/react-vite": ^8.4.7
  "@sushiswap/tines": ^1.0.11
  "@thirdweb-dev/engine": ^0.0.16
  "@types/jsonwebtoken": ^9.0.7
  "@types/node": ^22.10.1
  "@types/react": ^18.3.13
  "@types/react-dom": ^18.3.1
  "@types/uuid": "^10.0.0"
  "@vitejs/plugin-react": ^4.3.4
  "@wagmi/core": ^2.15.2
  abitype: ^1.0.7
  autoprefixer: ^10.4.20
  "aws-kms-signer": ^0.5.3
  clsx: ^2.1.1
  dotenv: ^16.4.7
  "dotenv-cli": ^7.4.4
  electron: ^31.1.2
  "electron-builder": ^25.1.7
  "electron-vite": ^2.3.0
  express: ^4.21.0
  fastify: ^5.1.0
  husky: ^9.1.7
  i18next: ^24.0.5
  "i18next-browser-languagedetector": ^8.0.0
  "input-otp": ^1.4.1
  jsdom: ^25.0.1
  jsonwebtoken: ^9.0.2
  "jwks-rsa": ^3.1.0
  "jwt-decode": ^4.0.0
  knip: ^5.39.2
  lint-staged: ^15.2.10
  pino: ^9.5.0
  pino-pretty: ^13.0.0
  postcss: ^8.4.49
  prisma: ^6.0.1
  react: ^18.2.0
  "react-dom": ^18.2.0
  "react-i18next": ^15.1.3
  storybook: ^8.4.7
  tailwindcss: ^3.4.16
  "tailwind-config-viewer": ^2.0.4
  "tailwindcss-animate": ^1.0.7
  "tailwind-merge": ^2.5.5
  thirdweb: ^5.74.0
  tsup: 8.3.0 # --watch mode broken with Fastify in later versions
  turbo: ^2.3.3
  typescript: ^5.7.2
  uuid: ^11.0.3
  viem: 2.21.53 # matches Thirdweb version to satisfy getAwsKmsAccount types
  vite: ^6.0.3
  vitest: ^2.1.8
