packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

catalog:
  '@aws-sdk/client-kms': ^3.665.0
  '@biomejs/biome': ^1.9.3
  '@biomejs/cli-linux-x64': ^1.9.3
  '@changesets/cli': ^2.27.9
  '@esbuild/linux-x64': ^0.24.0
  '@radix-ui/react-dialog': ^1.1.2
  '@radix-ui/react-visually-hidden': ^1.1.0
  '@rollup/rollup-linux-x64-gnu': ^4.24.0
  '@storybook/addon-essentials': ^8.3.5
  '@storybook/react': ^8.3.5
  '@storybook/react-vite': ^8.3.5
  '@sushiswap/tines': ^1.0.11
  '@types/jsonwebtoken': ^9.0.7
  '@types/node': ^22.7.4
  '@types/react': ^18.2.64
  '@wagmi/core': ^2.13.8
  abitype: ^1.0.6
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  concurrently: ^9.0.1
  husky: ^9.1.6
  i18next: ^23.15.1
  'i18next-browser-languagedetector': ^8.0.0
  'input-otp': ^1.2.4
  jsonwebtoken: ^9.0.2
  'jwt-decode': ^4.0.0
  knip: ^5.31.0
  lint-staged: ^15.2.10
  postcss: ^8.4.47
  react: ^18.2.0
  'react-i18next': ^15.0.2
  storybook: ^8.3.5
  tailwindcss: ^3.4.13
  'tailwind-config-viewer': ^2.0.4
  'tailwindcss-animate': ^1.0.7
  'tailwind-merge': ^2.5.3
  thirdweb: ^5.60.1
  tsup: ^8.3.0
  tsx: ^4.19.1
  typescript: 5.6.2
  viem: ^2.21.18
  vite: 5.4.8
  vitest: ^2.1.2
