packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

catalog:
  "@aws-sdk/client-kms": ^3.682.0
  "@aws-sdk/client-secrets-manager": ^3.682.0
  "@biomejs/biome": ^1.9.4
  "@biomejs/cli-linux-x64": ^1.9.4
  "@changesets/cli": ^2.27.9
  "@electron-toolkit/preload": ^3.0.1
  "@electron-toolkit/tsconfig": ^1.0.1
  "@electron-toolkit/utils": ^3.0.0
  "@esbuild/linux-x64": ^0.24.0
  "@fastify/cors": ^10.0.0
  "@fastify/swagger": ^9.2.0
  "@fastify/swagger-ui": ^5.1.0
  "@fastify/type-provider-typebox": ^5.0.1
  "@prisma/client": ^5.22.0
  "@radix-ui/react-dialog": ^1.1.2
  "@radix-ui/react-visually-hidden": ^1.1.0
  "@rollup/rollup-linux-x64-gnu": ^4.24.0
  "@sentry/node": ^8.37.1
  "@sinclair/typebox": ^0.33.17
  "@storybook/addon-essentials": ^8.4.2
  "@storybook/react": ^8.4.2
  "@storybook/react-vite": ^8.4.2
  "@sushiswap/tines": ^1.0.11
  "@thirdweb-dev/engine": ^0.0.16
  "@types/jsonwebtoken": ^9.0.7
  "@types/node": ^22.7.8
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@types/uuid": "^10.0.0"
  "@vitejs/plugin-react": ^4.3.3
  "@wagmi/core": ^2.14.1
  abitype: ^1.0.6
  autoprefixer: ^10.4.20
  "aws-kms-signer": ^0.5.3
  clsx: ^2.1.1
  "decimal.js-light": ^2.5.1
  dotenv: ^16.3.1
  "dotenv-cli": ^7.4.1
  electron: ^31.1.2
  "electron-builder": ^25.1.7
  "electron-vite": ^2.3.0
  express: ^4.21.0
  fastify: ^5.1.0
  husky: ^9.1.6
  i18next: ^23.16.4
  "i18next-browser-languagedetector": ^8.0.0
  "input-otp": ^1.4.1
  jsdom: ^25.0.1
  jsonwebtoken: ^9.0.2
  "jwt-decode": ^4.0.0
  knip: ^5.36.2
  lint-staged: ^15.2.10
  pino: ^9.5.0
  pino-pretty: ^11.3.0
  postcss: ^8.4.47
  prisma: ^5.22.0
  react: ^18.2.0
  "react-dom": ^18.2.0
  "react-i18next": ^15.1.0
  storybook: ^8.4.2
  tailwindcss: ^3.4.14
  "tailwind-config-viewer": ^2.0.4
  "tailwindcss-animate": ^1.0.7
  "tailwind-merge": ^2.5.4
  thirdweb: ^5.65.2
  tsup: 8.3.0 # --watch mode broken with Fastify in later versions
  turbo: ^2.2.3
  typescript: ^5.6.3
  uuid: ^11.0.2
  viem: 2.21.35 # matches Thirdweb version to satisfy getAwsKmsAccount types
  vite: ^5.4.10
  vitest: ^2.1.4
