packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

catalog:
  '@biomejs/biome': ^1.9.3
  '@biomejs/cli-linux-x64': ^1.9.3
  '@changesets/cli': ^2.27.9
  '@esbuild/linux-x64': ^0.24.0
  '@rollup/rollup-linux-x64-gnu': ^4.24.0
  '@types/node': ^22.7.4
  concurrently: ^9.0.1
  husky: ^9.1.6
  knip: ^5.31.0
  lint-staged: ^15.2.10
  tsup: ^8.3.0
  tsx: ^4.19.1
  typescript: 5.6.2
  vite: 5.4.8
  vitest: ^2.1.2
