services:
  db-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DATABASE_NAME}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
