name: Deploy Login
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        options:
          - development
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy development
        if: ${{ inputs.environment == 'development' }}
        run: flyctl deploy --config ./packages/login/fly.toml --app tdk-login-dev --remote-only --build-secret dotenv="${{ secrets.ENV_DEV }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy production
        if: ${{ inputs.environment == 'production' }}
        run: flyctl deploy --config ./packages/login/fly.toml --remote-only --build-secret dotenv="${{ secrets.ENV_PROD }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
