name: Deploy Login
on:
  workflow_dispatch:
  push:
    paths:
      - "apps/login/**"
      - "packages/**"
    branches:
      - main
    tags:
      - login-v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "${{ startsWith(github.ref, 'refs/tags/') }} === 'true' ? 'production' : 'development'"
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --config ./apps/login/fly.toml --app ${{ vars.LOGIN_APP_NAME }} --remote-only --build-secret dotenv="${{ secrets.LOGIN_ENV }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
