name: Deploy Login
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        options:
          - development
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --config ./apps/login/fly.toml --app ${{ vars.LOGIN_APP_NAME }} --remote-only --build-secret dotenv="${{ secrets.LOGIN_ENV }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
