name: Deploy API
on:
  workflow_dispatch:
  push:
    paths:
      - "apps/api/**"
      - "packages/**"
    branches:
      - main
      - terraform
    tags:
      - api-v*
permissions:
  id-token: write
  contents: read
env:
  ECR_REPOSITORY: 665230337498.dkr.ecr.us-west-2.amazonaws.com/development-identity
  AWS_ROLE_ARN: arn:aws:iam::665230337498:role/development-identity-github-actions
  AWS_REGION: us-west-2
  ECS_SERVICE: development-identity-service
  ECS_CLUSTER: development-identity-cluster
  ENVIRONMENT: development
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/tags/') && 'production' || 'development' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        run: |
          docker build -t $IMAGE_TAG -f ./apps/api/Dockerfile .
          docker push $IMAGE_TAG
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./apps/api/.aws/task-definition-${{ env.ENVIRONMENT }}.json
          container-name: web
          image: ${{ steps.build-image.outputs.image }}
          environment-variables: |
            AWS_REGION=${{ env.AWS_REGION }}
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
